buildscript {
    repositories {
    	mavenCentral()
	    maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
		maven { setUrl("https://repo.spring.io/milestone") }
		}
}

plugins {
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'java'
	id 'com.vaadin'
}

repositories {
	mavenCentral()
	maven { setUrl("https://maven.vaadin.com/vaadin-prereleases") }
	maven { setUrl("https://repo.spring.io/milestone") }
	maven { setUrl("https://maven.vaadin.com/vaadin-addons") }
}

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
}

dependencies {
	implementation('com.vaadin:vaadin-spring-boot-starter')
    testImplementation("com.vaadin:vaadin-testbench-junit5:$vaadinVersion")
	testRuntimeOnly("org.junit.platform:junit-platform-engine:1.12.2")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.12.2")
}

dependencyManagement {
	imports {
		mavenBom "com.vaadin:vaadin-bom:$vaadinVersion"
	}
}

test {
    useJUnitPlatform()
    filter{
		includeTestsMatching "com.example.test.*"
    }
}

// This task runs all tests (unit + integration) when -Pit is passed
tasks.register('integrationTest', Test) {
    onlyIf { project.hasProperty('it') }
    description = 'Runs all tests including TestBench (enabled only with -Pit)'
    group = 'verification'
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    shouldRunAfter test
    systemProperty "com.vaadin.testbench.Parameters.headless", System.getProperty("com.vaadin.testbench.Parameters.headless", "false")
    systemProperty "com.vaadin.testbench.Parameters.chromeOptions", System.getProperty("com.vaadin.testbench.Parameters.chromeOptions", "")
	doFirst {
        println "Remember to start the application before running integration tests"
        println "Run 'gradle bootRun' in another terminal before running these tests"
    }
}